### ISSUE TITLE
What version of Autohotkey should I install locally?

### ISSUE THREAD

**Issue by codemicro** [Gum-Joe/2Keys#19]
If at all?

Should I install the latest (1.1 I think) or 2 alpha?

**Comment by Gum-Joe** [comment]
No need to install locally, as 2Keys downloads the version of AHK (AutoHotkey) it needs (2 alpha).

More info:
- If you want to run hotkeys outside of 2Keys, install the latest 1.x version
- 2Keys uses 2 alpha as the DLL version of it (AutoHotKey_H) works better with 2Keys
- 2Keys provides the ability to test hotkeys without pressing any buttons on a mapped keyboard:
```
2Keys fire <keyboard name> <hotkey>
```
I.e. (this is only supported on the server)
```
2Keys fire numpad NUM1
```
This will run the AutoHotkey function you've associated with that key in the config file.

**Comment by codemicro** [comment]
Fantastic - thank you.

**Comment by Gum-Joe** [comment]
You're welcome!
