### ISSUE TITLE
The command used to build the detector does not build said detector

### ISSUE THREAD

**Issue by codemicro** [Gum-Joe/2Keys#23]
> To build the detector:
> 
```$ cd detector
$ pip3 install -r required.txt
```

only installs the dependencies, and not the actual package.

**Comment by Gum-Joe** [comment]
Well, there's no command that actually builds the detector (except packaging it).  It's more for development and working on it. Does this work:

"To build the detector (after installing [Pipenv](https://github.com/pypa/pipenv)) (for development purposes):
```
$ cd detector
$ pipenv install
$ pipenv shell
```
You can then install it in the Pipenv shell's PATH with `pip link -e .`.

If you want to install it globally, so you can use it with the 2Keys `systemctl` services:
```
$ cd detector
$ pipenv lock -r > required_tmp.txt
$ pip3 install -r required_tmp.txt
$ pip3 link -e .
```
Note that with this 2Keys and its dependencies will be installed for the entire system.
"

BTW general tip: When you see i.e. `pip install` this almost always will install the dependencies (i.e. `npm install`, `yarn install`, `gem install`), `-r ...` is just pip's way of specifing what to install.  The link command seems to be the way of getting a local dir onto PATH (or at least, this is the case for `npm`, `yarn` and `pip` do)

**Comment by Gum-Joe** [comment]
@codemicro Any updates on this?

**Comment by codemicro** [comment]
No - I had not tried it, instead just swapping out changed files. Since it's all working now and I don't want to break it somehow, I am going to leave it be.

**Comment by codemicro** [comment]
Although, as mentioned in #30 I may test a clean install soonish, so I'll report back if I do.

**Comment by Gum-Joe** [comment]
Ok, BTW `v0.4.1` has been released to npm, which contains updates to dependencies to fix a server lodash vulnerability (though not to PyPI as I haven't got round to it)

**Comment by codemicro** [comment]
Roger. Will update.

**Comment by codemicro** [comment]
Maybe publish in the security tab?

**Comment by Gum-Joe** [comment]
Also a good idea, thanks

**Comment by Gum-Joe** [comment]
@codemicro You ok if I close this issue?

**Comment by codemicro** [comment]
Go ahead.
