### ISSUE TITLE
How to add  3rd 4th 5th keyboard etc?

### ISSUE THREAD

**Issue by PotatoJet** [Gum-Joe/2Keys#56]

**Comment by Gum-Joe** [comment]
Hello! Thank you for checking out 2Keys!
I have now realized I have not written any documentation regarding how to add more than one keyboard.  I have therefore began writing one and will post a link here once done.

**Comment by Gum-Joe** [comment]
I have now written up instructions here:
https://github.com/Gum-Joe/2Keys/blob/master/docs/ADD_KEYBOARD.md

I apologise if they have (grammar) mistakes; I wrote them up very quickly.

**Comment by TaranGenius** [comment]
> I have now written up instructions here:
> https://github.com/Gum-Joe/2Keys/blob/master/docs/ADD_KEYBOARD.md
> 
> I apologise if they have (grammar) mistakes; I wrote them up very quickly.

Thank you for your kind message.I will try to see if it works.Hold on,my brother.

**Comment by Gum-Joe** [comment]
@PotatoJet Does this issue still need to be open?

**Comment by PotatoJet** [comment]
No,thanks.You are a good man.
